# docker-compose.yml
version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: xss_db
      MYSQL_USER: xss_user
      MYSQL_PASSWORD: xss_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" # Opzionale, solo se vuoi accedere al DB esternamente
    networks:
      - app-network

  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge